DROP TABLE [kpi_bank_marketing].[DIM_AGE] 
DROP TABLE [kpi_bank_marketing].[DIM_CAMPAIGN]
DROP TABLE [kpi_bank_marketing].[DIM_CONTACT]
DROP TABLE [kpi_bank_marketing].[DIM_DEFAULT]
DROP TABLE [kpi_bank_marketing].[DIM_EDUCATION]
DROP TABLE [kpi_bank_marketing].[DIM_EMPLOYED]
DROP TABLE [kpi_bank_marketing].[DIM_HOUSING]
DROP TABLE [kpi_bank_marketing].[DIM_JOB]
DROP TABLE [kpi_bank_marketing].[DIM_LOAN]
DROP TABLE [kpi_bank_marketing].[DIM_MARITAL]
DROP TABLE [kpi_bank_marketing].[DIM_POUTCOME]
DROP TABLE [kpi_bank_marketing].[DIM_Y]


------------------CREAR TABLAS

CREATE TABLE [kpi_bank_marketing].[DIM_AGE](
	[ID_AGE] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_AGE] PRIMARY KEY NONCLUSTERED 
(
	[ID_AGE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_CAMPAIGN](
	[ID_CAMPAIGN] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_CAMPAIGN] PRIMARY KEY NONCLUSTERED 
(
	[ID_CAMPAIGN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_CONTACT](
	[ID_CONTACT] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_CONTACT] PRIMARY KEY NONCLUSTERED 
(
	[ID_CONTACT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_DEFAULT](
	[ID_DEFAULT] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_DEFAULT] PRIMARY KEY NONCLUSTERED 
(
	[ID_DEFAULT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_EDUCATION](
	[ID_EDUCATION] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_EDUCATION] PRIMARY KEY NONCLUSTERED 
(
	[ID_EDUCATION] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_EMPLOYED](
	[ID_EMPLOYED] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_EMPLOYED] PRIMARY KEY NONCLUSTERED 
(
	[ID_EMPLOYED] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_HOUSING](
	[ID_HOUSING] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_HOUSING] PRIMARY KEY NONCLUSTERED 
(
	[ID_HOUSING] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_JOB](
	[ID_JOB] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_JOB] PRIMARY KEY NONCLUSTERED 
(
	[ID_JOB] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_LOAN](
	[ID_LOAN] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_LOAN] PRIMARY KEY NONCLUSTERED 
(
	[ID_LOAN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_MARITAL](
	[ID_MARITAL] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_MARITAL] PRIMARY KEY NONCLUSTERED 
(
	[ID_MARITAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_POUTCOME](
	[ID_POUTCOME] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_POUTCOME] PRIMARY KEY NONCLUSTERED 
(
	[ID_POUTCOME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [kpi_bank_marketing].[DIM_Y](
	[ID_Y] [int] NOT NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_ID_Y] PRIMARY KEY NONCLUSTERED 
(
	[ID_Y] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

--------------------------INSERT DIM-------------------------------
INSERT INTO [kpi_bank_marketing].[DIM_AGE]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_AGE]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_AGE] WHERE [DIM_AGE].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_AGE].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_CAMPAIGN]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_CAMPAIGN]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_CAMPAIGN] WHERE [DIM_CAMPAIGN].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_CAMPAIGN].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_CONTACT]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_CONTACT]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_CONTACT] WHERE [DIM_CONTACT].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_CONTACT].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_DEFAULT]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_DEFAULT]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_DEFAULT] WHERE [DIM_DEFAULT].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_DEFAULT].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_EDUCATION]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_EDUCATION]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_EDUCATION] WHERE [DIM_EDUCATION].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_EDUCATION].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_EMPLOYED]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_EMPLOYED]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_EMPLOYED] WHERE [DIM_EMPLOYED].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_EMPLOYED].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_HOUSING]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_HOUSING]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_HOUSING] WHERE [DIM_HOUSING].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_HOUSING].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_JOB]
SELECT 
[STG_JOB].[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_JOB].[DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[POC_DEACEROS].[staging_bank_marketing].[STG_JOB]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_JOB] WHERE [DIM_JOB].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_JOB].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [STG_JOB].[DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_LOAN]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_LOAN]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_LOAN] WHERE [DIM_LOAN].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_LOAN].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_MARITAL]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_MARITAL]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_MARITAL] WHERE [DIM_MARITAL].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_MARITAL].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_POUTCOME]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_POUTCOME]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_POUTCOME] WHERE [DIM_POUTCOME].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_POUTCOME].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

INSERT INTO [kpi_bank_marketing].[DIM_Y]
SELECT 
[ID_DESC]
,RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [DESCRIPCION], '.',' '), '-', ' ') )))
FROM 
[staging_bank_marketing].[STG_Y]
WHERE 
NOT EXISTS ( SELECT DESCRIPCION FROM [kpi_bank_marketing].[DIM_Y] WHERE [DIM_Y].DESCRIPCION = RTRIM(LTRIM(UPPER ( REPLACE (  REPLACE ( [STG_Y].[DESCRIPCION], '.',' '), '-', ' ') ))) )
AND [DESCRIPCION] IS NOT NULL
ORDER BY 1

------------CREAR FACT------------------

USE [POC_DEACEROS]
GO

/****** Object:  Table [kpi_bank_marketing].[FACT_MARKETING]    Script Date: 22/10/2024 04:19:52 p. m. ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[kpi_bank_marketing].[FACT_MARKETING]') AND type in (N'U'))
DROP TABLE [kpi_bank_marketing].[FACT_MARKETING]
GO

/****** Object:  Table [kpi_bank_marketing].[FACT_MARKETING]    Script Date: 22/10/2024 04:19:52 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [kpi_bank_marketing].[FACT_MARKETING](
	[ID_AGE] [int] NULL,
	[ID_JOB] [int] NULL,
	[ID_MARITAL] [int] NULL,
	[ID_EDUCATION] [int] NULL,
	[ID_DEFAULT] [int] NULL,
	[ID_HOUSING] [int] NULL,
	[ID_LOAN] [int] NULL,
	[ID_CONTACT] [int] NULL,
	[MONTH] [nvarchar](10) NULL,
	[DAY_OF_WEEK] [nvarchar](10) NULL,
	[DURATION] [int] NOT NULL,
	[ID_CAMPAIGN] [int] NOT NULL,
	[PDAYS] [int] NOT NULL,
	[PREVIOUS] [int] NOT NULL,
	[ID_POUTCOME] [int] NULL,
	[EMP_VAR_RATE] [float] NULL,
	[CONS_PRICE_IDX] [float] NULL,
	[CONS_CONF_IDX] [float] NULL,
	[EURIBOR3M] [float] NULL,
	[ID_EMPLOYED] [int] NULL,
	[ID_Y] [int] NULL,
	[T_CONVERSION] [float] NULL,
	[N_CONTACT] [int] NULL
) ON [PRIMARY]
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_AGE])
REFERENCES [kpi_bank_marketing].[DIM_AGE] ([ID_AGE])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_CAMPAIGN])
REFERENCES [kpi_bank_marketing].[DIM_CAMPAIGN] ([ID_CAMPAIGN])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_CONTACT])
REFERENCES [kpi_bank_marketing].[DIM_CONTACT]([ID_CONTACT])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_DEFAULT])
REFERENCES [kpi_bank_marketing].[DIM_DEFAULT]([ID_DEFAULT])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_EDUCATION])
REFERENCES [kpi_bank_marketing].[DIM_EDUCATION]([ID_EDUCATION])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_EMPLOYED])
REFERENCES [kpi_bank_marketing].[DIM_EMPLOYED]([ID_EMPLOYED])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_HOUSING])
REFERENCES [kpi_bank_marketing].[DIM_HOUSING] ([ID_HOUSING])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_JOB])
REFERENCES [kpi_bank_marketing].[DIM_JOB] ([ID_JOB])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_LOAN])
REFERENCES [kpi_bank_marketing].[DIM_LOAN]([ID_LOAN])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_MARITAL])
REFERENCES [kpi_bank_marketing].[DIM_MARITAL]([ID_MARITAL])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_POUTCOME])
REFERENCES [kpi_bank_marketing].[DIM_POUTCOME]([ID_POUTCOME])
GO

ALTER TABLE [kpi_bank_marketing].[FACT_MARKETING]  WITH CHECK ADD FOREIGN KEY([ID_Y])
REFERENCES [kpi_bank_marketing].[DIM_Y]([ID_Y])
GO

------------------------------------------------------
